services:
  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
    environment:
      - ENVIRONMENT=docker
    command: npm run start
    extra_hosts:
      - "host.docker.internal:host-gateway"  

  frontend:
    build:
      context: ./front
    ports:
      - "8100:8100"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lecycle.com
      PGADMIN_DEFAULT_PASSWORD: Testtest96-
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network

volumes:
  pgadmin_data:  

networks:
  app_network:
    name: app_network
    driver: bridge