services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: lecycle_db
      POSTGRES_USER: lecycle_user
      POSTGRES_PASSWORD: Testtest96-
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

  backend:
    image: arsenkubat/lecycle-backend:latest  
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://lecycle_user:Testtest96-@postgres:5432/lecycle_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=lecycle_user
      - DB_PASSWORD=Testtest96-
      - DB_NAME=lecycle_db
      - JWT_SECRET=${JWT_SECRET:-defaultsecret123} 
    depends_on:
      - postgres
    restart: unless-stopped 

  frontend:
    image: arsenkubat/lecycle-frontend:latest  
    ports:
      - "8100:8100"
    networks:
      - app_network
    environment:
      - ENVIRONMENT=production 
      - API_URL=http://backend:3000  
      - GOOGLE_CLIENT_ID=801627083778-37s8egjl71ftjs1aojhms17l2vvpj02s.apps.googleusercontent.com
      - GOOGLE_MAP_API=AIzaSyAVlY_KrrKefvnX9hwOO-alBCajjMDfxa8
    restart: unless-stopped  

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: kubatarsen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Testtest96-
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    name: app_network
    driver: bridge