services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: lecycle_db
      POSTGRES_USER: lecycle_user
      POSTGRES_PASSWORD: Testtest96-
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

  backend:
    image: arsenkubat/lecycle-backend:latest
    ports:
      - "127.0.0.1:3000:3000" 
    networks:
      - app_network
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://lecycle_app:HomeCycl@Lyon2024$@postgres:5432/lecycle_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=lecycle_app
      - DB_PASSWORD=HomeCycl@Lyon2024$
      - DB_NAME=lecycle_db
      - JWT_SECRET=${JWT_SECRET:-defaultsecret123} 
    depends_on:
      - postgres
    restart: unless-stopped 

  frontend:
    image: arsenkubat/lecycle-frontend:latest
    ports:
      - "127.0.0.1:8080:80"    
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - ENVIRONMENT=production 
      - API_URL=https://lecyclelyonnais.fr/api
    restart: unless-stopped  

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: kubatarsen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2024SecurePass!
    ports:
      - "127.0.0.1:5050:80"    
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    name: app_network
    driver: bridge