services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: lecycle_db
      POSTGRES_USER: lecycle_user
      POSTGRES_PASSWORD: Testtest96-
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build: ./back
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - ENVIRONMENT=production
    depends_on:
      - postgres
    restart: unless-stopped 

  frontend:
    build: ./front
    ports:
      - "8080:80"  
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - ENVIRONMENT=production 
      - API_URL=https://lecyclelyonnais.fr/api
    restart: unless-stopped  

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: kubatarsen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Testtest96-
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    name: app_network
    driver: bridge